openapi: 3.0.4
info:
  title: Fibonacci Generator
  description: >-
    Fibonacci Generator is a tool for generating Fibonacci sequence numbers. It
    can generate sequences by count or up to a maximum value, with options to
    start from any position in the sequence.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/fibonaccigenerator:
    get:
      summary: Generate by Count
      description: Generate a specific number of Fibonacci numbers
      operationId: fibonaccigenerator
      parameters:
        - name: count
          in: query
          schema:
            type: integer
          required: true
          description: Number of Fibonacci numbers to generate
          example: 10
        - name: startfrom
          in: query
          schema:
            type: integer
          required: false
          description: Start from this position in the sequence
          example: 0
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  sequence:
                    - 0
                    - 1
                    - 1
                    - 2
                    - 3
                    - 5
                    - 8
                    - 13
                    - 21
                    - 34
                  count: 10
                  start_from: 0
                  first_value: 0
                  last_value: 34
                  sum: 88
                  ratios:
                    - 1.666667
                    - 1.6
                    - 1.625
                    - 1.615385
                    - 1.619048
                  golden_ratio_approximation: 1.619048
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
